import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/component/Header";
import Footer from "@/app/component/Footer";
import { ReduxProvider } from "@/app/component/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white text-gray-600 dark:bg-zinc-950 dark:text-white`}>
        <ReduxProvider>
        <Header />
          {children}
        </ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
